version: "3.7"
services:
  apirest-full:
    container_name: apirest-full
    image: apirest-full:v1
    build:
      context: .
    ports:
      - "3001:3001"
    networks:
      - proyectos-app
networks:
  proyectos-app: